### ISSUE TITLE
todo notes

### ISSUE THREAD

**Issue by travi** [travi/javascript-scaffolder#87]
when there are known TODOs after scaffolding completion, they should be shown as output. hopefully this can serve as a list of next items to build into the scaffolder, but there are still times where things might be skipped that are needed before the project can successfully build etc

- [ ] environment variables https://github.com/travi/javascript-scaffolder/issues/55
~~- [ ] reinstall `husky@next`~~
- [x] commit
~~- [ ] create the github repo~~
- [x] push to remote
- [ ] enable travis integration (if not enabled for all repos. can this be determined?)
- [ ] add greenkeeper-keeper webhook
- [ ] enable greenkeeper
~~- [ ] move the greenkeeper badge to the contributing group~~
- [x] add the travis build status badge manually (for private projects only)
- [x] remove `tests/unit/canary-test.js` once a real test has been added
